version: '3'
services:
  katanataggerbot:
    container_name: katanataggerbot
    build: ./
    # or build this image, push to dockerhub.com and set
    # image: ......
    restart: unless-stopped
    environment:
      - token=     # 6256855944:AAEvfoexkpJ_Y0tPkwdEP2JYW1uza-SSudQ
      - owner_id=  # 5622660844
